# Generated by Django 5.0 on 2026-10-04 16:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title_target', models.CharField(blank=True, max_length=255, null=True)),
                ('job_file', models.FileField(blank=True, null=True, upload_to='job_requirements_pdf/')),
                ('job_description_text', models.TextField()),
                ('compatibility_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('semantic_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('skill_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('experience_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('education_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('compatibility_level', models.CharField(max_length=50)),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='resumes.resume')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
